# Generated by Django 5.2.9 on 2025-12-30 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('period', models.CharField(max_length=10)),
                ('classification', models.CharField(default='Present', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('student_id', 'date', 'period')},
            },
        ),
    ]
