# Generated by Django 5.2.10 on 2026-01-28 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 10, 33, 24, 140060, tzinfo=datetime.timezone.utc)),
        ),
    ]
