# Generated by Django 5.2.11 on 2026-02-05 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 5, 14, 1, 10, 10916, tzinfo=datetime.timezone.utc)),
        ),
    ]
